// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxFz1VKOALXpXyHDApQEkzGIs8CjIT-LE',
    appId: '1:508856739693:web:417444f6eabae54a1c1c64',
    messagingSenderId: '508856739693',
    projectId: 'fooddeliveryapp-174ad',
    authDomain: 'fooddeliveryapp-174ad.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-174ad.appspot.com',
    measurementId: 'G-Z7LH84GN4H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQHiEQN0Z7Tu5PS9YcoPx8t7ozYqwJYjc',
    appId: '1:508856739693:android:c290241df751cdb71c1c64',
    messagingSenderId: '508856739693',
    projectId: 'fooddeliveryapp-174ad',
    storageBucket: 'fooddeliveryapp-174ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApbbxzeyVPbetWRvaQoHonBCCyr5djFE0',
    appId: '1:508856739693:ios:896761cc1648b5f61c1c64',
    messagingSenderId: '508856739693',
    projectId: 'fooddeliveryapp-174ad',
    storageBucket: 'fooddeliveryapp-174ad.appspot.com',
    iosBundleId: 'com.example.delv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApbbxzeyVPbetWRvaQoHonBCCyr5djFE0',
    appId: '1:508856739693:ios:896761cc1648b5f61c1c64',
    messagingSenderId: '508856739693',
    projectId: 'fooddeliveryapp-174ad',
    storageBucket: 'fooddeliveryapp-174ad.appspot.com',
    iosBundleId: 'com.example.delv',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxFz1VKOALXpXyHDApQEkzGIs8CjIT-LE',
    appId: '1:508856739693:web:55a92438c66ebc361c1c64',
    messagingSenderId: '508856739693',
    projectId: 'fooddeliveryapp-174ad',
    authDomain: 'fooddeliveryapp-174ad.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-174ad.appspot.com',
    measurementId: 'G-SRG87HDP4V',
  );
}
